### ISSUE TITLE
دیالوگ باکس نباشد

### ISSUE THREAD

**Issue by majidjamhsidi** [mirshahbazi/MAMPersianDatePicker#1]
سلام ، چطور میشه بدون دیالوگ بطوری که روی یک اکتیویتی باشه ازش استفاده کرد ؟

**Comment by mirshahbazi** [comment]
سلام این برنامه ‌ذاتا به صورت دیالوگ طراحی شده و برای استفاده آن به شکلهای دیگر حتما از سورس خود لایبریری استفاده و تغییرات خود را اعمال نمایید
